development:
  adapter: mysql
  database: ezlearnz_development
  user: root
  password: plan46s
  socket: /var/run/mysqld/mysqld.sock
  
test:
  adapter: mysql
  database: ezlearnz_test
  user: root
  password: plan46s
  socket: /var/run/mysqld/mysqld.sock
  
production:
  adapter: mysql
  database: ezlearnz_production
  user: root
  password: plan46s
  socket: /var/run/mysqld/mysqld.sock
